#!/bin/env bash

# ban_common - features common to all ban scripts
# https://github.com/TonyGravagno/ban-the-bad
# (C) 2022 Tony Gravagno : MIT Licenced : Irony acknowledged

###############

./ban_subnet 45.142.120
./ban_subnet 193.169.253
