#!/bin/env bash

# ban_common - features common to all ban scripts
# https://github.com/TonyGravagno/ban-the-bad
# (C) 2022 Tony Gravagno : MIT Licenced : Irony acknowledged

###############

# ban_range - ban a range of IPs : "ban_range 1.2.3.x-1.2.3.y"
CHAIN=range
. ban_common

ban_this $IP
