#!/bin/env bash

# ban_subnet - ban a class D IP block, 0-255 : "ban_subnet 1.2.3"
# https://github.com/TonyGravagno/ban-the-bad
# (C) 2020 Tony Gravagno : MIT Licenced : Irony acknowledged

CHAIN=subnet
. ban_common

ban_this "$IP.0/24"
