#!/bin/env bash

# ban_common - features common to all ban scripts
# https://github.com/TonyGravagno/ban-the-bad
# (C) 2022 Tony Gravagno : MIT Licenced : Irony acknowledged

###############

# ban_subnet - ban a class D IP block, 0-255 : "ban_subnet 1.2.3"

CHAIN=subnet
. ban_common

ban_this "$IP.0/24"
