#!/bin/env bash

# ban_common - features common to all ban scripts
# https://github.com/TonyGravagno/ban-the-bad
# (C) 2022 Tony Gravagno : MIT Licenced : Irony acknowledged

###############

# ban_single - ban one IP address : "ban_single 1.2.3.4"

CHAIN=single
. ban_common

ban_this $IP
