#!/bin/env bash

# ban_common - features common to all ban scripts
# https://github.com/TonyGravagno/ban-the-bad
# (C) 2022 Tony Gravagno : MIT Licenced : Irony acknowledged

###############

./ban_single 212.70.149.37
./ban_single 129.199.133.8
./ban_single 178.128.36.26
